<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.36" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.1.2" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.1.2" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.1.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Stripe.net" Version="48.0.0" />
    <PackageReference Include="Twilio" Version="7.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RideAway.Application\RideAway.Application.csproj" />
  </ItemGroup>

</Project>
